nfephp-org/sped-cte

config/cte_ws2.xml

Segue mudanças nos links do serviço de homologação do SEFAZ MS, conforme: http://www.cte.ms.gov.br/desativacao-em-19jan2016-homologacao-e-01032016-producao-do-ambiente-de-autorizacao-do-conhecimento-de-transporte-eletronico-ct-e/

atualizado links de serviços no ambiente de homologação de MS

---

src/Tools.php

Corrigindo devido não estar batendo com os valores de comparação na classe BaseTools que por consequência não permitia encontrar os caminhos para os xmls, que esta atualmente assim:
private function zGetXmlUrlPath($tipo)
{
$path = '';
if ($tipo == 'nfe') {
$path = $this->aConfig['pathXmlUrlFileNFe'];
if ($this->modelo == '65') {
$path = str_replace('55', '65', $path);
} else {
$path = str_replace('65', '55', $path);
}
} elseif ($tipo == 'cte') {
$path = $this->aConfig['pathXmlUrlFileCTe'];
} elseif ($tipo == 'mdfe') {
$path = $this->aConfig['pathXmlUrlFileMDFe'];
} elseif ($tipo == 'cle') {
$path = $this->aConfig['pathXmlUrlFileCLe'];
}
$pathXmlUrlFile = NFEPHP_ROOT
. DIRECTORY_SEPARATOR
. 'config'
. DIRECTORY_SEPARATOR
. $path;
return $pathXmlUrlFile;
}

ajustado valor do parametro 'tipo' do método 'assinaDoc()' para lowercase

---

src/Make.php

Segundo Manual CTe v2.00 os campos xSeg e nApol não são obrigatórios no xml.

ajustado indicador de obrigatoriedade na tag seguro

---

examples/testaCartaCorrecao.php
src/Tools.php

Este pull request trata da correção do evento Carta de Correção CTe, visto que não era possível gerar o xml com o protocolo da mesma.
- Inclusão de variável
- Modificações no método "zSefazEvento" para atender parâmetros do manual CTe, visto que estava com base na NFe.
- Assim como o método "sefazCartaCorrecao", onde foram removidos parâmetros que julguei serem desnecessários com base nas outras classes NFePHP.
Testado e validado em ambiente de produção.

Correção - Evento Carta de Correção

---

src/Tools.php

Segue método corrigido conforme pr #61 
Apenas para considerações:
De acordo com manual CT-e versão 2.00 os eventos não possuem tratamento em lote, como é o caso da NF-e (cStat=128), neste caso o protocolo não era adicionado ao evento.
Também exclusos parâmetros desnecessários ($siglaUF e $cnpj) do método **sefazCartaCorrecao**

Ajuste carta de correção

---

examples/testaCartaCorrecao.php
src/Tools.php

Este pr contém um ajuste no método que faz o envio da carta de correção. 
Para o evento carta de correção do CT-e é necessário informar outras correções que foram enviadas previamente. Sem isto a carta de correção enviada anteriormente será susbtiuída pela próxima.

Ajustes carta de correção

---

config/cte_ws2.xml

Corrige o erro na consulta por chave. Só testei pra MG, por isso não troquei dos outros estados. Caso alguém tenha como fazer o teste e o debug retornar: Message part {http://www.portalfiscal.inf.br/cte/wsdl/CteConsultaProtocolo}cteDadosMsg was not recognized.  (Does it exist in service WSDL?) Basta alterar de CteConsultaProtocolo para CteConsulta

Atualização de "operation" da Consulta por Chave

---

src/Tools.php

Método replicado a partir do projeto sped-nfe. Teste validado a partir do exemplo presente no diretório examples/testaInutilizaCte.php. Regra negócio validada de acordo com o presente no Manual de Orientação do Contribuinte - Versão 2.00a (pag. 53)

adicionado metodo zValidParamInut para uso em sefazInutiliza

---

schemas/PL_CTe_300/tiposGeralCTe_v3.00.xsd

estou alterando a  validação da inscrição estadual e string genérica pois nesse formato não valida em servidores linux, a forma que estou postando é a mesma da versão 2.0 que era compativel em servidores win e lin, e que funciona também na versão 3.0

ajuste para validar

---

tests/Auxiliar/IdentifyTest.php
tests/Auxiliar/ResponseTest.php
tests/MakeTest.php
tests/ToolsTest.php

Usei a [PSR-1](http://www.php-fig.org/psr/psr-1/#namespace-and-class-names) enquanto extendendo a classe `PHPUnit TestCase`. Isso irá nos ajudar quando migrarmos para o `PHPUnit 6`, que [não mais suporta _snake case namespaces_](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).

PHPUnit TestCase com PSR-1

---

composer.json
src/Make.php

- Nos casos de Expedidor, Recebedor e Destinatário a inscrição estadual poderá ser vazia de acordo com manual. Deste modo a tag <IE/> não será criada.
- O composer.json deve indicar apenas o nome do repositório oficial nfephp-org/sped-cte no packagist, favor não renomear com forks.

IE opcional

---

schemes/PL_CTe_300/tiposGeralCTe_v3.00.xsd

O pattern antigo causava problemas na validação usando o xsd pelo PHP, como por exemplo não permitir campos strings com apenas dois caracteres.

Ajuste no schema geral TString

---

storage/wscte_3.00_mod57.xml

Correção da operação para consulta de CTe nos estados do MT e PR.
Creio que o estado do MS também precise de ajuste, mas não consegui acessar o WSDL para confirmar.
No formato em que se encontra, ao consultar o status da chave nos respectivos estados, a Sefaz estava retornando o erro:
```
<soapenv:Fault>
<soapenv:Code>
<soapenv:Value>soapenv:Server.userException</soapenv:Value>
</soapenv:Code>
<soapenv:Reason>
<soapenv:Text xml:lang="en">	</soapenv:Text>
</soapenv:Reason>
<soapenv:Detail>
<ns1:hostname xmlns:ns1="http://xml.apache.org/axis/">tapajos04.sefaz.mt.gov.br</ns1:hostname>
</soapenv:Detail>
</soapenv:Fault>
```

Correção Operação de Consulta CTe - Estados MT e PR

---

src/Make.php

como consta no documento http://www.cte.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=7V%20i40m98sg=
pagina 47 a tag tpNav não é obrigatória

removendo a obrigatorieda da tag tpNav

---

src/Tools.php

Para o estado do MT ao tentar fazer o manifesto de Prestação do Serviço em Desacordo, estava retornando a critica "402 - Rejeicao : XML da area de dados com codificacao diferente de UTF-8." da sefaz. Ao entrar em contato explicou que nao sao permitidos os caracteres especiais da $tagAdic na linha 540. Após a remoção foi manifestado corretamente.

Remover Caracter Especial Manifesto

---

src/Common/Tools.php
src/Factories/QRCode.php

O método de criação de QRCode não estava considerando XML de CTeOS, mas somente de CTe. Deste modo a busca pela tag raiz CTe retornava null, levantando erro no método $cte->insertBefore($infCTeSupl, $signature);

[UPD] Pega tag raiz CTeOS quando o modelo de documento for 67.

---

src/Tools.php

O contador possuiu um certificado para seu cpf e esta autorizado na tag AutXml, portanto liberado para fazer o download dos xmls relacionados ao seu cpf, mas a api dava erro de Falha no Schema xml retornado pela sefaz, pois o mesmo nao estava preparado para receber cpf, somente cnpj, tentei manter a compatibiliadade nao trocando o nome da variavel, somente validando caso seja cpf ou cnpj, preenche o xml pela tag correta.

download de xml com cpf

---

composer.json
src/Common/Standardize.php
src/Tools.php

Na classe standardize não estava verificando se existe a tag cteDistDFeInteresseResponse.
Na classe Tools método sefazDownload, o nome do serviço é case sensitive.

Correções da biblioteca 

---

src/Make.php

A função Monta(), inseria os subgrupos <idDocAntPap> e <idDocAntEle> dentro da mesma tag <idDocAnt>, o que gerava falha no schema, pois pelo  diagrama da SEFAZ, cada tag <idDocAnt> pode conter apenas 1 desses dois subgrupos.

Correção de condicionais para inclusão do grupo idDocAntPap no XML.

---

storage/wscte_3.00_mod57.xml

Correção URL QrCode MG Homologação
http://www.sped.fazenda.mg.gov.br/spedmg/cte/webservice/
Rejeição: 851 - Endereco do site da UF da Consulta via QR Code diverge do previsto

Correção URL QrCode MG Homologacao

---

src/MakeCTe.php
storage/wscte_4.00_mod57.xml

Para envio de CT-e substituição e complemento, ocorre a seguinte rejeição:
Expected is one of ( {http://www.portalfiscal.inf.br/cte}infCTeNorm, {http://www.portalfiscal.inf.br/cte}infCteComp ).
505 - Rejeicao : Grupo CTe de substituicao nao informado para o CT-e substituicao.
Verifiquei que na função **monta** do **MakeCTe.php**, para criar a tag **infCteComp**, está verificando se o **tpCTe** é **3** – substituição, porem o correto é **1** – complemento. 
Ainda para criar a tag **infCTeNorm**, está verificando se o **tpCTe** é **0** – normal ou **1** – complemento, correto é os **0** – normal e **3** – substituição.
Na montagem da tag **infCteSub** está verificando o **tpCTe** é **1** – complemento, sendo o correto o **3** – substituição
Foi removido um espaço em branco na URL de …

Correção para tag de substituição, rejeição nas tag de infCTeNorm e infCteComp

---

src/MakeCTe.php

Percebi que a tag vCargaAverb estava sendo gerada dentro do bloco infQ, quando deveria ser gerada no bloco infCarga.
Fiz o ajuste para gerar no local certo.

fix: move tag vCargaAverb da tag infQ para a tag  infCarga

---

src/Tools.php

O envio das tags latitude e longitude é opcional, mas no componente precisa que passe uma informação valida nas tags

Ajuste na latitude e longitude para envio do comprovante de entrega

---

src/MakeCTeOS.php

Ola, 
Verifiquei que ao enviar um **CT-e OS** com **Tipo 3 – substituição**, o grupo “**infCteSub**” não estava sendo criado no XML. Para correção foi modificado “**MakeCTeOS.php**” incluindo o grupo em questão como filho do grupo “**infCTeNorm**”. 
A falta deste grupo gera a rejeição: _505 - Rejeição: Grupo CT-e de Substituição não informado para o CT-e de Substituição_
Após a modificação, consegui autorizar alguns CT-e OS em homologação com estado **GO**, no estado de **MG** até a data está com problema para receber este tipo de CT-e OS. 
@cleitonperin

Informando grupo infCteSub no CT-e OS de Substituição

---

src/Tools.php

Conforme manual do CT-e 4.00:
Foi adicionado o trecho do evento de cancelamento da Prestação de Serviço em Descordo.
Os testes foram realizados para as UFs MS e MT.
Para não ser necessário incluir um novo parâmetro na sefazManifesta, o número do protocolo do evento foi enviado na xJust.

Adicionando evento de Cancelamento de Prestação de Serviço em Desacordo

---

src/MakeCTe.php

**xMotivo:** 646 -  Rejeicao :  CT-e emitido em ambiente de homologacao com Razao Social do remetente diferente de CTE EMITIDO EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL.
**Solução:** Remoção de tratamento de homologação para MT.
**Resultado:** Autorizado o Uso do CT-e
[CTe MT.txt](https://github.com/nfephp-org/sped-cte/files/14538749/CTe.MT.txt)

 MakeCTe - MT

---

storage/wscte_4.00_mod57.xml
storage/wscte_4.00_mod64.xml
storage/wscte_4.00_mod67.xml

Comunicado da Sefaz de MG
> Por motivos técnicos, a partir do dia 24/04/2025, a URL do QrCode do CTe será modificada. De hoje até dia 23/04/2025, a SEF-MG aceitará tanto a URL antiga quanto a nova. De 24/04/2025 em diante, apenas a URL nova será aceita, conforme descrito abaixo:
> 
> CTe (caminho: CTe -> infCTeSupl -> infCTeSupl):  
>   Url antiga: https://cte.fazenda.mg.gov.br/portalcte/sistema/qrcode.xhtml
>   Url nova: https://portalcte.fazenda.mg.gov.br/portalcte/sistema/qrcode.xhtml
> 
> Gentileza atentar-se ao prazo limite, pois após 23/04/2025 as URLs antigas não serão mais aceitas.
@cleitonperin @robmachado Poderiam verificar, por favor?

feat: Adiciona a nova URL do QrCode do CTe de MG
