nfephp-org/sped-cte

src/Make.php

tagICMS = Implementado as CST que estão disponiveis conforme manual.
tagExped e tagReceb = Ajustado a tagEmail que deve aparecer depois do grupo de endereço do Recebedor e Expedidor.

Ajustado tagICMS e tagExped e tagRem

---

README.md
examples/testaMakeCTe.php
src/BaseTools.php
src/Make.php
src/Tools.php

Add comentários no Make.php
Add Tag infCteComp para CTe complemento de valores
Ajuste no montaCTe() para adequar CTe complemento e CTe normal
Add filtro para não escrever tags IE ( inscrição estadual ) pois além do case 'ISENTO' existe o caso onde a pessoa(física ou exterior) não contribui com icms então a tag tem que ser omitida
Add na segTag() as tags xSeg, nApol e vCarga
Add veicTag quando o modal for do tipo Rodoviário
Add motoTag no leilaute Rodoviário
Add infCTeComp() chave do CT-e complementado ( chave de acesso de referencia )

Develop ( versão 2.0 )

---

install/certchk.php
install/criaJsonConfig.php
install/folderchk.php
install/index.php
install/nfephp.css
install/saveconfig.php

adicionar a pasta install ao projeto

add pasta install para gerar o arquivo config.json

---

examples/testaMakeCTe.php
src/Make.php
src/Tools.php

Colocando o Make no padrão da psr2

Correção PSR2

---

src/Make.php

Foi adicionada a Tag para o XML de código interno do veículo. Este campo é opcional para o XML.

Adicionado tag de Código Interno do Veículo que não tinha antes.

---

src/Make.php

Retirado os testes para enviar ou não a tag de IE.
A tag deve ser sempre enviada: com a IE ou ISENTO ou em branco (indicando não contribuinte)

Develop - Retirado teste da variável $IE

---

src/Tools.php

Comentado algumas linhas por não ter implementadas para funcionar.
Ajustado tipos de parâmetros e retorno.

Ajustado função de inutilizar numeração.

---

src/Make.php
src/Tools.php

- Adição de tags de CT-e de anulação

- Adição de tags de CT-e de anulação

---

src/Tools.php

Método replicado a partir do projeto sped-nfe. Teste validado a partir do exemplo presente no diretório examples/testaInutilizaCte.php

adicionado metodo zAddProtMsg para uso em sefazInutiliza

---

config/cte_ws3.xml

remoção de quebra de linha gerava erro na conexão com a SEFAZ

remoção de quebra de linha

---

examples/testaMakeCTe.php

teste de make na versão 3.0

---

src/Make.php

- Retiradas tags de veículos, motoristas e seguro, pois na versão 3.0 não tem mais estes campos.
- Adicionado tags de Diferencial de Alíquotas
- Adicionado tags para CT-e de Anulação (que já tinha na master)

Alterações e ajustes para versão 3.0

---

config/cte_ws3.xml
src/BaseTools.php
src/Make.php
src/Tools.php

- Ajustado serviços da receita para aceitar urls de comunicação.
- Ajustado Tools, BaseTools e Make para algumas funções específicas do CT-e OS.

Alterações para CT-e OS (modelo 67)

---

src/Make.php

- Ajustado o nome da tag do XML quando é CT-e complementar.

Ajuste para CT-e complementar v3.0

---

examples/testDistDFe.php
src/Tools.php
storage/autorizadores.json
storage/wscte_3.00_mod57.xml

Implementação do serviço CTeDistribuicaoDFe para busca da CTe, referenciado na issue #103. 
Também foram renomeadas as variáveis e métodos da classe src/Tools que estavam como nfe para cte.

V4.0 - Ajustes no método sefazDistDFe para utilizar o serviço CTeDistribuicaoDFe

---

src/Common/Standardize.php

Inclusão da tag "retConsStatServCte" no Standardize.

Inclusão de tag no Standardize

---

src/Auxiliar/Response.php
src/Make.php

Segundo a documentação temos alguns valores opcionais na resposta, um destes valores é o protocolo do evento, adicionei no retorno estas informações quando elas vierem, caso contrario continuamos com o retorno padrão já existente.

Adicionando campos opcionais do retorno de evento

---

storage/wscte_3.00_mod57.xml

Fonte: http://www.cte.fazenda.gov.br/portal/webservices.aspx

Protocolo deve ser HTTPS

---

src/Tools.php

Quando é CT-e OS deve ser o XML cteOSProc
quando é CT-e normal deve ser cteProc

Ajustado Proc para CT-e OS

---

schemes/PL_CTe_300/evPrestDesacordo_v3.00.xsd
schemes/PL_CTe_300/eventoCTeTiposBasico_v3.00.xsd
src/Tools.php
storage/wscte_3.00_mod57.xml

Estava tendo problemas para enviar Prestação de Serviço em Desacordo e precisei fazer as alterações do PR.
- No SefazManifesta, precisei adicionar uma variável com o estado do evento, onde deve ser informado o Estado do Evento do Emitente do CT-e. (Antes estava como AN e este serviço não existe no Ambiente Nacional).
- Aproveitei e atualizei os Schemas com a última versão da Receita Federal CT-e.

Evento de Prestação de Serviço em Desacordo

---

examples/testaMakeCTeOS.php
src/Common/Standardize.php
src/Common/Tools.php
src/Complements.php
src/Make.php
src/Tools.php

Esta atualização contém as seguintes alterações/inclusões:
1 - Inclusão de método para gerar CT-e OS (Este método estava presente na branch 3.0 porém ainda não havia sido refatorada para versão atual).
2 - Ajustes menores nas classes Standardize, Tools e Complements para atender ao modelo de CT-e 67
3 - Ajustes na classe Make que faz a geração do CT-e OS (Não foram feitas alterações em métodos e funcionalidades do modelo 57)
4 - Exemplo de geração CT-e OS
5 - Esta atualização resolve a issue #151

Inclusão de método para gerar CT-e OS

---

examples/testaMakeCTe.php
src/Make.php

Implementei o modal aéreo e incrementei os exemplos com os dados esperado para o modal e seus detalhes/possíveis valores. Também fiz alguns ajustes afim de validar erros no Travis.

Implementado Modal Aéreo

---

src/Tools.php

[UPD] Validação de CTe #174

---

examples/testaMakeCTe.php
src/Make.php

Adicionada a tag autXML, destinada a informar os autorizados a fazer download do XML.

Adicionada a tag autXML

---

src/Make.php

Ao adicionar a tag obsFisco, ocorre o seguinte erro:
```Undefined offset: -1```

Correção de erro ao adicionar tag obsFisco

---

schemes/PL_CTe_300/cteTiposBasico_v3.00.xsd

Quando tag IE do emit for vazia nao vai aparecer e não vai criticar

Tag IE do emit pode ser vazia (ISENTO)

---

src/Make.php

Indicação da Data/hora da viagem e tipo de
fretamento no CT-e OS

[INC] CT-e OS infFretam

---

src/Make.php

corrigindo valor tag vCargaAverb, a mesma esta no lugar errado, estava em infCarga e o segundo a documentação da sefaz deve está em infQ

corrigindo a tag valor da averbação

---

src/Make.php

a api tinha apenas o método taginfCteSub, mais entretanto não adicionava a tag ao xml

adicionado a tag infCteSub ao xml

---

src/Make.php

Verifiquei que somente tinha o rodo e o aereo e com isso adicionei o aquav.

adiconado tag para o Leiaute - Aquaviario

---

src/Make.php

Exclusão da tag pICMSInterPart do leiaute do CT-e

arrumando a partilha conforme nova norma técnica

---

src/Complements.php

adicionar o cancelamento no xml do cte

Complements registrar cancelamento. By phpanico

---

storage/wscte_3.00_mod57.xml

A operation do method cteConsultaCT do estado do MS foi alterada para CteConsulta. Anteriormente estava CteConsultaProtocolo.

Alterado operation do method cteConsultaCT do estado do MS

---

src/Common/Tools.php

validação do cte com base no scheme do modal em especifico

validação do cte com base no scheme do modal em especifico

---

README.md

Atualização da Versão da API

---

src/Make.php

Testa se a tag infdoc estiver null para não gerar o erro. Ajustado os possible da tagrodoos.

Ajuste tag infdoc e tagrodoos possible

---

storage/wscte_3.00_mod57.xml

Links obtidos por: https://dfe-portal.svrs.rs.gov.br/Cte/Servicos#SEFAZ%20S%C3%A3o%20Paulo%20/%20SEFAZ%20Virtual%20SP%20(SP/SVSP)-Produ%C3%A7%C3%A3o

Links WebService SVSP

---

src/Make.php

Alterado condição do IF, a anterior retornava out of index.

Correção de IF

---

src/Make.php

Criado leiaute do CTe Multimodal e tags inerentes.

Criado leiaute do CTe Multimodal

---

src/MakeCTe.php

-CTe - Correção Homologação RS
-CTe - CTE Substituição - Indicação Alteração Tomador

Correções CTE 4.0

---

src/MakeCTeOS.php

Adicionando informações do Fisco (TAG obsFisco)

Update MakeCTeOS.php adicionando informacoes do obsFisco

---

examples/testaCancelaIE.php
examples/testaIE.php
src/Tools.php

Adiciona eventos de Insucesso de Entrega de CTe (110190) e de Cancelamento de Insucesso de Entrega (110191), bem como os testes de ambos eventos

adiciona eventos de Insucesso de Entrega de CTe e de Cancelamento de Insucesso de Entrega

---

src/Tools.php

Corrige fechamento da tag xJustMotivo do evento de insucesso de entrega

corrige tag xJustMotivo

---

src/MakeCTe.php
src/MakeCTeOS.php

No código já existia a chamada da função mais a mesma não existia com isso apresentava um erro, adicionei a função seguindo o exmplo do projeto nfe.

Criação da função para criar o hash CSRT

---

src/MakeCTe.php

vTar modal Dutoviário com 6 casas decimais
